### ISSUE TITLE
Logging: print `message` as JSON, instead of wrapping into a string

### ISSUE THREAD

**Issue by mriccia** [aws-powertools/powertools-lambda-java#1508] opened 2023-11-08 17:06 UTC
**Is your feature request related to a problem? Please describe.**

The Powertools Logging functionality automatically wraps the messages into string, regardless of whether they are strings or objects.
Looking through the logs with CloudWatch logs is harder with the `message` being printed as a single string, and printing as JSON will also unlock other options (e.g. using CloudWatch insights to automatically discover fields).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeromevdl** [comment] 2023-11-10 14:29
I think this is a breaking change ==> v2

**Comment by scottgerring** [comment] 2023-11-13 08:00
This feels quite important. Is it really breaking and not a bug?
OTOH we are redoing the logging in v2 anyway, so there's a natural synergy there.

**Comment by jeromevdl** [comment] 2023-11-24 13:26
@jdoherty I'm taking this one. I'm working on the logging v2 anyway. Not sure that make sense you spend time on a pure log4j solution as I'm using slf4j now.

**Comment by jeromevdl** [comment] 2023-11-24 14:19
https://stackoverflow.com/questions/77543791/slf4j-and-log4j2-json-messages-escaped

**Comment by jeromevdl** [comment] 2023-11-27 17:13
will be part of #1435, using the [`PowertoolsResolver`](https://github.com/aws-powertools/powertools-lambda-java/blob/59342152f2f156c96396ead52c604a1fddcb2020/powertools-logging/powertools-logging-log4j/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/PowertoolsResolver.java#L174)

**Comment by jeromevdl** [comment] 2023-11-28 07:11
Discussion with Log4J: https://github.com/apache/logging-log4j2/discussions/2013

**Comment by scottgerring** [comment] 2023-12-13 13:12
@jeromevdl we should probably update this with resolution once you're done 👼

**Comment by jeromevdl** [comment] 2023-12-14 09:29
Based on the discussions with log4j guys, on this [issue](https://github.com/aws-powertools/powertools-lambda-java/issues/965), and after thinking a bit more about this, we won't log messages as JSON. Instead, we'll support advanced object as additional arguments (not using MDC which is limited to Strings), and log them as JSON (when that makes sense).

_Example_:
```java
Product product = new Product("id123456", "Name of the product", 234.5);

LOGGER.info("Some message", StructuredArguments.entry("key", product)); 

// can also use static import to make it lighter
LOGGER.info("Some message", entry("product", product));
```

will produce:

```json
{
    "message": "Some message",
    "product": {
        "id": "id123456", 
        "name": "Name of the product", 
        "price": 234.5
    }
}
```

Note there was no `{}` in the message, if you do this:
```java
LOGGER.info("My super product={}", entry("product", product));
```

will produce: 

```json
{
    "message": "My super product=[...]", // will use the object.toString()
    "product": {
        "id": "id123456", 
        "name": "Name of the product", 
        "price": 234.5
    }
}
```

Also working on other `StructuredArguments`:
- `entries` that will take a complete `Map`
- `array` that will take an `Object... objects`
- `json` that will take a raw json string

For the event and response, we'll use this instead of putting the event in the message.

**Comment by jeromevdl** [comment] 2023-12-14 09:43
No I need to implement some stuff. The `StructureArguments` thing and how they interpreted. It is supported with the logback-logstash-encoder but that's another library to add to the project...

**Comment by mriccia** [comment] 2023-12-14 09:46
My thoughts on this implementation are: 
Yes we are achieving the objective of printing out objects as JSON structures in the logs, which is the ultimate goal.
However the onus is now on the library user to ensure that they log this way every time they intend to log an object.

What will I do if I only want to log an object, without a string message?
Will it be `LOGGER.info("{}", entry("product", product));`?

**Comment by jeromevdl** [comment] 2023-12-14 09:48
You cannot log without a message. Or you can just log an empty message, but messages are always there (it's the basic of the loggers).

you should do `LOGGER.info("", entry("product", product));` but you will have an empty message in the logs...

**Comment by jeromevdl** [comment] 2023-12-14 09:50
we could actually check if the message is empty and not adding it to the log...

**Comment by mriccia** [comment] 2023-12-21 10:47
I am OK with this (would like to hear other views), even though I don't love the syntax. 

> we could actually check if the message is empty and not adding it to the log... but a log without a message is a bit weird

Agree that it would be weird to print a log message, without any message

**Closed** 2024-02-29 07:13 UTC
Labels: v2, priority:2
