### ISSUE TITLE
Propagation of request information across thread boundaries

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1670] opened 2024-06-24 11:58 UTC
**Is your feature request related to a problem? Please describe.**
In #1620 we are looking at implementing parallel processing for batches to reduce clock time spent handling batch requests. As part of this, we have started considering _what happens when we rely on thread-local storage to propagate request context_. In the batch case this affects immediately tracing, but more broadly, I think it is worth considering how PT might help support multi-threaded processing, or at the very least, avoid complicating it.

I would suggest the next step here is to consider all areas of PT that _use_ thread local, and if that can be avoided. This may very well be v2 "cleanup style" work. Next, what other areas of PT may benefit from supporting multi-threaded processing, and what would the impact of this be?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by scottgerring** [comment] 2024-06-24 11:59
There's a [great comment](https://github.com/aws-powertools/powertools-lambda-java/pull/1620#issuecomment-2083456666) from @humanzz that outlines some of the issues that happen with thread pooling in general in a Java-Lambda environment.

**Comment by jeromevdl** [comment] 2024-07-04 11:45
Somehow duplicate of #1671

**Closed by jeromevdl** 2024-07-04 11:45 UTC
Labels: triage
